name: Deploy ta-aswan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write

concurrency:
  group: ta-aswan-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Build and Deploy
    uses: nestorzamili/gha-workflows/.github/workflows/deploy-container.yml@v1.5.0
    with:
      image-name: ta-aswan
      container-name: ta-aswan
      volume: /var/lib/ta-aswan/writable:/var/www/html/writable
      health-cmd: "wget -qO- --header=User-Agent:Docker-Healthcheck http://127.0.0.1/health || exit 1"
      docker-context-name: ta-aswan-vm
      environment: production
      env-file-container-path: /var/www/html/.env
    secrets: inherit
